[package]
name = "ductor-macros"
version = "0.1.3"
edition = "2024"
description = "zero-cost typestate lib: procedural macros"
license = "MIT OR Apache-2.0"
repository = "https://tangled.org/bushyice.com/ductor"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
proc-macro2 = "1.0"
