[package]
name = "ductor"
version = "0.1.0"
edition = "2024"
description = "ductor"
license = "MIT OR Apache-2.0"
repository = "https://github.com/bushyice/ductor"

[dependencies]
ductor-core = { version = "0.1.0", path = "../ductor-core" }
ductor-macros = { version = "0.1.0", path = "../ductor-macros" }
