[package]
name = "ductor"
version = "0.1.4"
edition = "2024"
description = "zero-cost typestate lib"
license = "MIT OR Apache-2.0"
repository = "https://tangled.org/bushyice.com/ductor"
readme = "../README.md"

[dependencies]
ductor-core = { version = "0.1.3", path = "../ductor-core" }
ductor-macros = { version = "0.1.3", path = "../ductor-macros" }
