//! A raw example as a demo for how the core traits function
//! and what gets generated from the macros

use ductor::*;

/// family marker, only one per state machine.
/// generated by `#[typestate]` on the enum.
pub struct Door;
impl StateFamily for Door {}

/// state variants.
/// each gets an `IsState` impl linking back to the family.
#[derive(Debug)]
pub struct Open;
impl IsState for Open {
  type Family = Door;
}

#[derive(Debug)]
pub struct Closed;
impl IsState for Closed {
  type Family = Door;
}

/// allowed transitions, gets a `Transition` impl per `#[transition(...)]`.
///
/// `Requirements = NoRequirement` means no capability is needed.
impl Transition<Closed, Open> for Door {
  type Requirements = NoRequirement;
}
impl Transition<Open, Closed> for Door {
  type Requirements = NoRequirement;
}

/// a concrete capability (what `#[cap]` generates).
#[derive(Debug)]
pub struct HasKey;
impl Capability for HasKey {}

/// what `#[unit]` generates.
///
/// `State` and `Caps` generics are added automatically by the macro;
/// here we write them out by hand.
#[derive(Debug)]
pub struct Lock<State = UnknownState, Caps = UnknownCaps> {
  pub state: State,
  pub caps: Caps,
}

/// placeholder so the struct can be named before generics are fixed.
/// not actually used once you provide concrete State/Caps.
type UnknownState = ();
type UnknownCaps = Caps<()>;

/// family marker for the unit itself.
pub struct LockFamily;
impl StateFamily for LockFamily {}

impl<State, Caps> Unit for Lock<State, Caps> {
  type State = State;
  type Caps = Caps;
  type Family = LockFamily;

  fn state(&self) -> &State {
    &self.state
  }
  fn caps(&self) -> &Caps {
    &self.caps
  }
}

impl<State, Caps> Lock<State, Caps> {
  pub fn new(state: State, caps: Caps) -> Self {
    Lock { state, caps }
  }
}

impl<State, Caps> Lock<State, Caps> {
  /// transition from the current state to a target state.
  /// only compiles when `Self: CanTransitionTo<Target, Caps, F, M>`.
  pub fn transition<Target, CapMarker, F>(
    self,
    f: F,
  ) -> <Self as CanTransitionTo<Target, Caps, F, CapMarker>>::Out
  where
    Self: CanTransitionTo<Target, Caps, F, CapMarker>,
  {
    <Self as CanTransitionTo<Target, Caps, F, CapMarker>>::perform_transition(self, f)
  }
}

impl<Caps, F, From, To, CapMarker> CanTransitionTo<To, Caps, F, CapMarker> for Lock<From, Caps>
where
  From: IsState,
  To: IsState,
  From::Family: Transition<From, To>,
  Caps: Satisfies<<From::Family as Transition<From, To>>::Requirements, CapMarker>,
  F: FnOnce(From) -> To,
{
  type Out = Lock<To, Caps>;

  fn perform_transition(self, f: F) -> Self::Out {
    Lock {
      state: f(self.state),
      caps: self.caps,
    }
  }
}

impl<S: IsState + 'static, Caps> Lock<S, Caps> {
  pub fn into_unknown(self) -> Lock<Of<<S as IsState>::Family>, Caps> {
    Lock {
      state: Of::new(self.state),
      caps: self.caps,
    }
  }
}

impl<State: 'static, Caps> Lock<State, Caps> {
  pub fn into_unknown_all(self) -> Lock<Of<LockFamily>, Caps> {
    Lock {
      state: Of::new_unchecked(self.state),
      caps: self.caps,
    }
  }
}

impl<F: StateFamily, Caps> Lock<Of<F>, Caps> {
  pub fn as_some<S: IsState<Family = F> + 'static>(&self) -> Option<&S> {
    self.state.as_some::<S>()
  }

  pub fn is<S: IsState<Family = F> + 'static>(&self) -> bool {
    self.state.is::<S>()
  }

  pub fn into_some<S: IsState<Family = F> + 'static>(self) -> Option<Lock<S, Caps>> {
    let state = self.state.into_some::<S>()?;
    Some(Lock {
      state,
      caps: self.caps,
    })
  }

  pub fn trim_unknown<S: IsState<Family = F> + 'static>(self) -> Option<Lock<S, Caps>> {
    self.into_some::<S>()
  }
}

fn main() {
  // start in Closed with HasKey capability.
  let lock = Lock::new(Closed, Caps((HasKey,)));

  // the type is `Lock<Closed, Caps<(HasKey,)>>`, no erased state.
  // transition to Open, then back to Closed.
  let lock = lock.transition(|Closed| Open);
  let lock = lock.transition(|Open| Closed);

  println!("lock after round-trip: {lock:?}");

  let erased: Lock<Of<Door>, Caps<(HasKey,)>> = lock.into_unknown();
  assert!(erased.is::<Closed>());

  let recovered: Lock<Closed, Caps<(HasKey,)>> = erased.trim_unknown().unwrap();
  println!("recovered: {recovered:?}");
}
